stages:
  ingest:
    cmd: python -m src.catops.data.ingest
    deps:
      - src/catops/data/ingest.py
    outs:
      - data/processed/cat
      - data/processed/not_cat

  validate:
    cmd: python src/catops/data/validate.py
    deps:
      - src/catops/data/validate.py
      - data/processed/cat
      - data/processed/not_cat
    outs:
      - data/processed/metadata.csv
