[project]
name = "purr-duction-pipeline"
version = "0.1.0"
description = "Am I a Cat? — binary image classification MLOps pipeline"
authors = [
    {name = "Afonso Costa",email = "afonsocosta90@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "dvc[gs,s3] (>=3.67.1,<4.0.0)",
    "hydra-core (>=1.3.2,<2.0.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "pandas (>=2.2,<3)",
    "pillow (>=12.2.0,<13.0.0)",
    "tqdm (>=4.67.3,<5.0.0)",
    "mlflow (<3.13)",
    "scikit-learn (>=1.5.0,<2.0.0)",
    "prefect (>=3.0.0)",
    "greenlet (>=3.5.0,<4.0.0)"
]

[tool.poetry.group.dev.dependencies]
pytest = ">=9.0.3,<10.0.0"
pytest-cov = ">=7.1.0,<8.0.0"
black = ">=26.3.1,<27.0.0"
ruff = ">=0.15.12,<0.16.0"
mypy = ">=2.0.0,<3.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry]
package-mode = false

